[theme]
base = "light"
primaryColor = "#3F729B"           # A deep blue similar to Instagram's header
backgroundColor = "#FFFFFF"        # Clean white for the background
secondaryBackgroundColor = "#E6F4F9" # Light blue shade for secondary elements
textColor = "#2E2E2E"              # Dark gray for primary text for readability
secondaryTextColor = "#6E6E6E"     # Medium gray for secondary text
font = "sans serif"                # A sans-serif font for a modern look
